#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

DOTFILES_DIR="$(dirname $(readlink $HOME/.vimrc))"
export DOTFILES=${DOTFILES_DIR}

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# I use git status way more than git stash, so override `gs` alias
alias gs="git status"
alias gaa="git add --all"
alias gap="git add -p"
alias gd="git diff"
alias gdc="git diff --cached"

# Re-enable fasd aliases
alias a='fasd -a'        # any
alias s='fasd -si'       # show / search / select
alias d='fasd -d'        # directory
alias f='fasd -f'        # file
alias sd='fasd -sid'     # interactive directory selection
alias sf='fasd -sif'     # interactive file selection
alias z='fasd_cd -d'     # cd, same functionality as j in autojump
alias zz='fasd_cd -d -i' # cd with interactive selection

# git flow
alias gffs='git flow feature start'
alias gfff='git flow feature finish'

export LC_ALL=en_GB.UTF-8
export LANG=en_GB.UTF-8

# Custom RubyGem global location
export GEM_HOME=$HOME/.gem
export PATH=$GEM_HOME/bin:$PATH

function xc {
  xcode_proj=`ls | grep "\.xc" | sort -r | head -1`
  if [[ `echo -n $xcode_proj | wc -m` == 0 ]]
  then
    echo "No xcworkspace/xcodeproj file found in the current directory."
  else
    echo "Found $xcode_proj"
    open "$xcode_proj"
  fi
}

function update {
  RED='\033[0;31m'
  GREEN='\033[0;32m'
  YELLOW='\033[0;33m'
  NC='\033[0m'
  echo "${YELLOW}Updating dotfiles...${NC}\n"
  pushd $DOTFILES > /dev/null 2>&1
  if ! [[ `git pull` ]]; then
    echo "\n${RED}Dotfiles:${NC} something went wrong"
    popd > /dev/null 2>&1
    return
  fi
  if ! [[ `git submodule update` ]]; then
    echo "\n${RED}Prezto:${NC} something went wrong"
    popd > /dev/null 2>&1
    return
  fi
  echo "${GREEN}Done!${NC}"
  popd > /dev/null 2>&1
}
